### ISSUE TITLE
install wasp

### ISSUE THREAD

**Issue by rinaldi6109** [mavaddat/wasp#3]
Totally newbie here and... how do I install & run wasp module?

**Comment by SirWobbyTheFirst** [comment]
Yeah, I'd also appreciate knowing how you are supposed to install this module.

**Comment by mavaddat** [comment]
[How to install WASP as module in PowerShell](https://github.com/mavaddat/wasp/blob/master/How%20to%20install%20WASP%20as%20module%20in%20PowerShell.md)

**Comment by Ketenks** [comment]
I could not find the correct Wasp.dll or there was an error in the build. I got this error while following the directions:
`PS C:\Users\> Import-Module -name WASP
Import-Module : Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\WASP\WASP.dll' or
one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module -name WASP
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand`

The directions are vague and only say "releases" directory without there being an actual directory called releases. I searched around and found two different dll's in the zip and tried both of them and both gave this same error. I'm on Windows 10.

**Comment by chaoscreater** [comment]
I have the same issue as Ketenks

**Comment by Ketenks** [comment]
Awesome thanks

**Comment by mavaddat** [comment]
> I have the same issue as Ketenks. I figured it out, you have to unblock the .dll file in the Properties.

Thank you. I will add this to the documentation.
